a=$(grep "cis" /etc/security/audit_event | awk -F: '{ print $2 }' | egrep 'AUE_CHROOT|AUE_FCHROOT|AUE_NICE|AUE_PFEXEC|AUE_PRIOCNTLSYS|AUE_SETEGID|AUE_SETEUID|AUE_SETGID|AUE_SETPGID|AUE_SETPPRIV|AUE_SETREGID|AUE_SETREUID|AUE_SETSID|AUE_SETUID' | sort)

echo $a